# Zsh configuration for macOS

# Stop here for non-interactive shells.
[[ -o interactive ]] || return

# History
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=10000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_REDUCE_BLANKS

# Completion
autoload -Uz compinit
compinit

# NVM
export NVM_DIR="$HOME/.nvm"
[[ -s "$NVM_DIR/nvm.sh" ]] && source "$NVM_DIR/nvm.sh"

# FZF
if (( $+commands[fzf] )); then
  if [[ -r "$HOME/.fzf.zsh" ]]; then
    source "$HOME/.fzf.zsh"
  elif [[ -r /opt/homebrew/opt/fzf/shell/key-bindings.zsh ]]; then
    source /opt/homebrew/opt/fzf/shell/key-bindings.zsh
    [[ -r /opt/homebrew/opt/fzf/shell/completion.zsh ]] &&
      source /opt/homebrew/opt/fzf/shell/completion.zsh
  fi
fi

# Atuin (optional)
if (( $+commands[atuin] )); then
  eval "$(atuin init zsh)"
elif [[ -x "$HOME/.atuin/bin/atuin" ]]; then
  eval "$("$HOME/.atuin/bin/atuin" init zsh)"
fi

# Aliases
alias ls='eza --icons'
alias ll='eza -lah --icons --git'
alias la='eza -a --icons'
alias lt='eza --tree --level=2 --icons'
alias grep='rg'

alias cls='clear'
alias ..='cd ..'
alias ...='cd ../..'
alias mkdir='mkdir -pv'

alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline --graph --decorate'

alias dps='docker ps'
alias dc='docker compose'

# Prompt and directory navigation
(( $+commands[starship] )) && eval "$(starship init zsh)"
if (( $+commands[zoxide] )); then
  eval "$(zoxide init zsh)"
  alias cd='z'
fi
# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/fraga/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
